# Generated by Django 4.0.4 on 2022-05-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luwa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packtype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
